### ISSUE TITLE
Transfer repo to @dlang-community

### ISSUE THREAD

**Issue by PetarKirov** [dlang-community/awesome-d#87]
Hey @zhaopuming, thanks for starting this awesome repo and for maintaining it for so long. This is a very valuable resource which helps showcase some of the coolest D projects and is indispensable for new comers!
I think it would be in D's best interest if we transfer the repo to the @dlang-community organization. If you agree, you will of course remain as a maintainer, but other members of the community would also be able to approve pull requests and update the files.
In addition to opening the maintenance to more people, this would also make the repo more visible.

What do you think?

**Comment by zhaopuming** [comment]
OK, thanks for taking care of this repo. How do I proceed to transfer it?

**Comment by PetarKirov** [comment]
You can find explanation on how to do it here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account

In summary, you need to go to `Settings` tab (of this repo) -> `Danger Zone` (scroll down on the main `Options` page) -> `Transfer` and then on `New owner` field type @dlang-community (though you may need to delete the `@` sign in front):
![image](https://user-images.githubusercontent.com/3475150/100717038-32917e80-33c2-11eb-9e43-3100888ff502.png)

I just sent you an invite to the dlang-community organization:

![image](https://user-images.githubusercontent.com/3475150/100717438-b51a3e00-33c2-11eb-958f-f92d8dc0537a.png)


So please accept the invitation, which you should have just received on your email.

**Comment by PetarKirov** [comment]
Hey @zhaopuming can you take another look please?

**Comment by zhaopuming** [comment]
Hi @PetarKirov , I've transferred this repo to dlang-community, please have a look and see if there's any problem?

**Comment by PetarKirov** [comment]
Thank you, everything good! I think we can now close this issue ;)
