### ISSUE TITLE
Diamond framework issues

### ISSUE THREAD

**Issue by katafrakt** [dlang-community/awesome-d#98]
Hey! Under full stack web framework there is a Diamond framework listed. However, it links to a website with incorrect SSL certificate. Plus it's rather inactive (only one commit in 2020). I would suggest:

* Changing the link to https://github.com/DiamondMVC/Diamond
* Maybe somehow marking it as inactive, although I think you don't generally do that in this repo
* Or maybe even remove it, I'm not sure

**Comment by kubo39** [comment]
:+1: for removal, seems unmaintained.

**Comment by bausshf** [comment]
See my comment here: https://github.com/dlang-community/awesome-d/pull/100#issuecomment-875412867

But basically it was inactive because I was working on creating a successor for it.
